---
abstract: 'Aspect-Oriented Programming (AOP) for Perl'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.29
  Test::More: 0.70
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Aspect
name: Aspect
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Devel::Symdump: 2.04
  Params::Util: 1.00
  Sub::Install: 0.92
  Sub::Uplevel: 0.2002
  Task::Weaken: 1.00
  perl: 5.8.2
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Aspect
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Aspect
version: 0.43
