# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Aspect
version:      0.09_03
version_from: lib/Aspect.pm
installdirs:  site
requires:
    Benchmark::Timer:              0.5
    Devel::Symdump:                2.03
    Test::Class:                   0.065

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
