--- 
abstract: AOP for Perl
author: 
  - Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0.70
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Aspect
no_index: 
  directory: 
    - inc
    - t
requires: 
  Benchmark::Timer: 0
  Devel::Symdump: 0
  Test::Class: 0
  perl: 5.8.2
version: 0.14
