---
abstract: 'Aspect-oriented programming (AOP) for Perl'
author:
  - 'Marcel GrE<uuml>nauer <marcel@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0.28
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Aspect
name: Aspect
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Devel::Symdump: 2.04
  perl: 5.8.2
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Aspect
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Aspect
version: 0.16
